### ISSUE TITLE
Hi, I'd like to use tensorflow_serving_docker to make a face recognition model

### ISSUE THREAD

**Issue by xvdehao** [amiyapatanaik/tensorflow-serving-docker-image#1]
Hello, new to tensorflow serving, I have a question: if I want to handle my own model, I can change the config file?
And which parameters should be modified?
Any suggestions are very helpful to me thanks.

**Comment by amiyapatanaik** [comment]
Please refer to the serving your own model section in the readme. The process is very clearly explained. 
In short, you create your own model folder and put the config file inside and just mount this folder is the -v flag in Docker. 

```
docker run --name tfserve_deploy -p 9000:9000 -d -v /pathtolocal/models:/models:ro amiyapatanaik/tfserve:optimized
```
