### ISSUE TITLE
Dockerfile ?

### ISSUE THREAD

**Issue by dcyoung** [amiyapatanaik/tensorflow-serving-docker-image#3]
Perhaps I missed it, but I didn't see a Dockerfile in the repo. Is there a place we can see the Dockerfile used to generate the docker image? 
Thanks!

**Comment by amiyapatanaik** [comment]
I'm sorry dcyoung.... I was just starting with docker and simply forgot to save the dockerfile. In case you manage to writeup one please do share.

**Comment by dcyoung** [comment]
@amiyapatanaik  No worries. Thanks for the quick response. I'll be sure to post back if I write a relevant dockerfile.
